server:
  port: 8083

spring:
  cloud:
    gateway:
      routes:
        - id: app-service
          uri: lb://APP-SERVICE
          predicates:
            - Path=/app/**
          filters:
            - AuthenticationFilter

        - id: restaurant-service
          uri: lb://RESTAURANT-SERVICE
          predicates:
            - Path=/restaurant/**
          filters:
            - AuthenticationFilter

        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/auth/**

  application:
    name: GATEWAY-SERVICE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    root: INFO